# Generated by Django 5.1.2 on 2024-11-04 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zybooks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ta",
            name="course",
            field=models.ForeignKey(
                default="None",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teaching_assistants",
                to="zybooks.course",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="ta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="course_as_ta",
                to="zybooks.user",
            ),
        ),
    ]
