# Generated by Django 5.1.2 on 2024-11-03 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zybooks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='id',
        ),
        migrations.AddField(
            model_name='content',
            name='content_name',
            field=models.CharField(default='Block01', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chapter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='content',
            name='block_type',
            field=models.CharField(blank=True, choices=[('text', 'Text'), ('image', 'Image')], max_length=10),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
