# Generated by Django 5.1.2 on 2024-11-06 06:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zybooks", "0002_rename_course_student_course_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentPoints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("point", models.IntegerField(default=0)),
                ("timestamp", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "block_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zybooks.content",
                    ),
                ),
                (
                    "chapter_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zybooks.chapter",
                    ),
                ),
                (
                    "course_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zybooks.course"
                    ),
                ),
                (
                    "question_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zybooks.question",
                    ),
                ),
                (
                    "section_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zybooks.section",
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zybooks.student",
                    ),
                ),
                (
                    "textbook_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zybooks.textbook",
                    ),
                ),
                (
                    "unique_activity_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zybooks.activity",
                    ),
                ),
            ],
        ),
    ]
