# Generated by Django 5.1.2 on 2024-11-04 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zybooks", "0003_alter_ta_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ta",
            name="course",
        ),
        migrations.AlterField(
            model_name="course",
            name="ta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="course_ta",
                to="zybooks.user",
            ),
        ),
    ]
