# Generated by Django 5.1.2 on 2024-10-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zybooks', '0003_user_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
