# Generated by Django 5.1.2 on 2024-11-03 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zybooks', '0003_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='block_type',
            field=models.CharField(blank=True, choices=[('text', 'Text'), ('image', 'Image'), ('a', 'Activities')], max_length=10),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
