# Generated by Django 5.1.2 on 2024-11-06 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zybooks", "0003_studentpoints"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="studentpoints",
            unique_together={
                (
                    "student_id",
                    "course_id",
                    "textbook_id",
                    "chapter_id",
                    "section_id",
                    "block_id",
                    "unique_activity_id",
                    "question_id",
                )
            },
        ),
    ]
