# Generated by Django 5.1.2 on 2024-11-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zybooks', '0004_alter_content_block_type_alter_content_content_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='block_type',
            field=models.CharField(blank=True, choices=[('text', 'Text'), ('image', 'Image'), ('activities', 'Activities')], max_length=10),
        ),
    ]
