# Generated by Django 5.1.2 on 2024-10-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zybooks', '0004_remove_user_id_alter_user_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
