# Generated by Django 5.1.2 on 2024-11-06 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zybooks", "0004_alter_studentpoints_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="activity_status",
        ),
    ]
