# Generated by Django 5.1.2 on 2024-11-03 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zybooks', '0005_alter_content_block_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='id',
        ),
        migrations.AddField(
            model_name='chapter',
            name='chapter_name',
            field=models.CharField(default='chap01', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
