# Generated by Django 5.1.2 on 2024-10-28 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zybooks', '0005_remove_course_id_alter_course_course_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='unique_token',
        ),
        migrations.AddField(
            model_name='course',
            name='course_token',
            field=models.CharField(default='TOKEN01', max_length=7, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('active', 'Active'), ('evaluation', 'Evaluation')], default='active', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('enrolled', 'Enrolled')], default='pending', max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zybooks.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zybooks.user')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
    ]
