# Generated by Django 5.1.2 on 2024-11-06 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zybooks', '0005_remove_student_activity_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textbook',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='textbook',
            field=models.ForeignKey(default=101, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zybooks.textbook'),
        ),
    ]
