# Generated by Django 5.1.2 on 2024-11-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zybooks', '0006_remove_chapter_id_chapter_chapter_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='option_1_label',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_2_label',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_3_label',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_4_label',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
