# Generated by Django 5.1.2 on 2024-10-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zybooks', '0006_remove_course_unique_token_course_course_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
