# Generated by Django 5.1.2 on 2024-10-28 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zybooks', '0007_alter_course_course_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('chapter_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('hidden', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=500)),
                ('read_status', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zybooks.user')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.FloatField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('hidden', models.BooleanField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zybooks.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('textbook_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='zybooks.course')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='textbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zybooks.textbook'),
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.IntegerField()),
                ('block_type', models.CharField(choices=[('Text', 'Text'), ('Image', 'Image')], max_length=5)),
                ('content_data', models.BinaryField()),
                ('hidden', models.BooleanField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zybooks.section')),
            ],
            options={
                'unique_together': {('section', 'content_id')},
            },
        ),
    ]
