# Generated by Django 5.1.2 on 2024-11-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zybooks', '0007_remove_question_option_1_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_number',
            field=models.CharField(default='ACT0', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
