# Generated by Django 5.1.2 on 2024-10-28 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zybooks', '0008_chapter_notification_section_textbook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='zybooks.course'),
        ),
    ]
