# Generated by Django 5.1.2 on 2024-10-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zybooks', '0009_alter_textbook_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='textbook_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
