# Generated by Django 5.1.2 on 2024-10-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zybooks', '0010_alter_textbook_textbook_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
