# Generated by Django 5.1.2 on 2024-10-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zybooks', '0011_alter_chapter_chapter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='block_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image')], max_length=5),
        ),
    ]
