# Generated by Django 5.1.2 on 2024-10-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zybooks', '0012_alter_content_block_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='content_data',
        ),
        migrations.RemoveField(
            model_name='content',
            name='id',
        ),
        migrations.AddField(
            model_name='content',
            name='image_data',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='content',
            name='text_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='block_type',
            field=models.CharField(blank=True, choices=[('text', 'Text'), ('image', 'Image')], max_length=5),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='content',
            name='hidden',
            field=models.BooleanField(blank=True),
        ),
    ]
