# Generated by Django 5.1.2 on 2024-10-30 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zybooks', '0013_remove_content_content_data_remove_content_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='textbook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zybooks.textbook'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('chapter', 'textbook', 'number')},
        ),
    ]
