# Generated by Django 5.1.2 on 2024-10-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zybooks', '0014_section_textbook_alter_section_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image_url',
            field=models.TextField(blank=True),
        ),
    ]
