# Generated by Django 5.1.2 on 2024-10-30 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zybooks', '0017_question_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zybooks.question'),
        ),
    ]
