# Generated by Django 5.1.2 on 2024-10-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zybooks', '0018_alter_activity_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
