# Generated by Django 5.1.2 on 2024-10-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zybooks', '0021_course_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='hidden',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
