# Generated by Django 5.1.2 on 2024-10-30 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zybooks", "0022_activity_hidden"),
    ]

    operations = [
        migrations.CreateModel(
            name="TA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "faculty_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faculty_supervised_tas",
                        to="zybooks.user",
                    ),
                ),
                (
                    "ta_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_tas",
                        to="zybooks.user",
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
