# Generated by Django 5.1.2 on 2024-10-30 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zybooks', '0023_remove_course_user_course_user_faculty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='user_faculty',
        ),
        migrations.RemoveField(
            model_name='course',
            name='user_ta',
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to='zybooks.user')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_faculty', to='zybooks.faculty'),
        ),
        migrations.CreateModel(
            name='TA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_pay', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hours_per_week', models.PositiveIntegerField()),
                ('associated_faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tas', to='zybooks.faculty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ta', to='zybooks.user')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='ta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_ta', to='zybooks.ta'),
        ),
    ]
