# Generated by Django 5.1.2 on 2024-10-30 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zybooks', '0024_remove_course_user_faculty_remove_course_user_ta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ta',
            name='user',
        ),
        migrations.AddField(
            model_name='ta',
            name='faculty',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_name', to='zybooks.user'),
        ),
        migrations.AddField(
            model_name='ta',
            name='ta',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ta_name', to='zybooks.user'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
