# Generated by Django 5.1.2 on 2024-10-30 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zybooks", "0025_alter_course_course_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ta",
            old_name="ta_id",
            new_name="ta_username",
        ),
    ]
