# Generated by Django 5.1.2 on 2024-10-30 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zybooks', '0028_alter_course_faculty_remove_ta_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zybooks.course'),
        ),
    ]
