# Generated by Django 5.1.2 on 2024-10-30 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zybooks', '0026_rename_ta_id_ta_ta_username'),
        ('zybooks', '0029_alter_textbook_course'),
    ]

    operations = [
    ]
