<<<<<<< HEAD
# Generated by Django 5.1.2 on 2024-10-31 03:16
=======
# Generated by Django 5.1.2 on 2024-10-31 03:24
>>>>>>> 51d3e6d2cdd7e1e9a86a72f9db2cbd0188b76695

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('zybooks', '0030_merge_20241030_1939'),
=======
        ("zybooks", "0030_merge_20241030_1936"),
>>>>>>> 51d3e6d2cdd7e1e9a86a72f9db2cbd0188b76695
    ]

    operations = [
        migrations.RemoveField(
<<<<<<< HEAD
            model_name='ta',
            name='faculty_id',
        ),
        migrations.RemoveField(
            model_name='ta',
            name='ta_username',
        ),
        migrations.AddField(
            model_name='ta',
            name='associated_faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tas', to='zybooks.user'),
        ),
        migrations.AddField(
            model_name='ta',
            name='hourly_pay',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ta',
            name='hours_per_week',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ta',
            name='ta',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ta_name', to='zybooks.user'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='hidden',
=======
            model_name="ta",
            name="faculty_id",
        ),
        migrations.RemoveField(
            model_name="ta",
            name="ta_username",
        ),
        migrations.AddField(
            model_name="ta",
            name="associated_faculty",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tas",
                to="zybooks.user",
            ),
        ),
        migrations.AddField(
            model_name="ta",
            name="hourly_pay",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="ta",
            name="hours_per_week",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ta",
            name="ta",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ta_name",
                to="zybooks.user",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="hidden",
>>>>>>> 51d3e6d2cdd7e1e9a86a72f9db2cbd0188b76695
            field=models.BooleanField(),
        ),
    ]
