# Generated by Django 5.1.2 on 2024-10-31 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zybooks", "0031_remove_ta_faculty_id_remove_ta_ta_username_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_capacity",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
