# Generated by Django 5.1.2 on 2024-10-31 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zybooks", "0035_alter_chapter_chapter_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="id",
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="chapter_id",
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name="section",
            name="section_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
