# Generated by Django 5.1.2 on 2024-10-31 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zybooks", "0036_chapter_id_alter_chapter_chapter_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="chapter_id",
            field=models.CharField(max_length=7),
        ),
    ]
