# Generated by Django 5.1.2 on 2024-11-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zybooks', '0037_alter_chapter_chapter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
