# Generated by Django 5.1.2 on 2024-11-02 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zybooks', '0039_activity_content_alter_activity_activity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zybooks.chapter'),
        ),
        migrations.AddField(
            model_name='content',
            name='textbook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zybooks.textbook'),
        ),
    ]
