# Generated by Django 5.1.2 on 2024-11-02 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zybooks', '0040_content_chapter_content_textbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='content',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zybooks.chapter'),
        ),
        migrations.AlterField(
            model_name='content',
            name='textbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zybooks.textbook'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('textbook', 'chapter_id')},
        ),
    ]
