# Generated by Django 5.1.2 on 2024-11-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zybooks', '0042_alter_chapter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='block_type',
            field=models.CharField(blank=True, choices=[('text', 'Text'), ('image', 'Image'), ('activity', 'Activity')], max_length=10),
        ),
        migrations.AlterField(
            model_name='section',
            name='number',
            field=models.CharField(max_length=20),
        ),
    ]
