# Generated by Django 5.1.2 on 2024-11-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zybooks", "0042_alter_chapter_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_token",
            field=models.CharField(max_length=7, null=True, unique=True),
        ),
    ]
