# Generated by Django 5.1.2 on 2024-11-02 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zybooks', '0043_alter_content_block_type_alter_section_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='content',
            name='textbook',
        ),
    ]
