# Generated by Django 5.1.2 on 2024-11-02 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zybooks", "0043_alter_course_course_token"),
        ("zybooks", "0044_remove_content_chapter_remove_content_textbook"),
    ]

    operations = []
