# Generated by Django 5.1.2 on 2024-11-02 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zybooks", "0044_remove_notification_notification_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_participation_points",
                    models.PositiveBigIntegerField(default=0),
                ),
                ("finished_activites", models.PositiveBigIntegerField(default=0)),
                (
                    "registered_couser_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zybooks.course"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zybooks.user"
                    ),
                ),
            ],
        ),
    ]
